### ISSUE TITLE
Suggest: Ability to index rows by only column letter (and not row number).

### ISSUE THREAD

**Issue by pnomolos** [pythonicrubyist/creek#61]
When you're iterating via `sheet#rows` it seems to me that being able to lookup values via on the column letter would be much simpler, so you don't have to keep track of the row number as well.

If this sounds like a good idea I'm more than willing to submit a patch.

**Comment by tedPen** [comment]
+1 for this, we probably wouldn't want to use this gem unless it has this capability. Ideally, I would want to be able to assign custom headers but if we can get letter based hashes would be great for us.

**Comment by pythonicrubyist** [comment]
Looking up values based on the column letter, the way I understand it, will require loading the whole XML to the memory. And that will slow down the gem when parsing very large files.

**Comment by gduprey** [comment]
Why would it require parsing any more of the XML than is already read?  Using sheets.row.each, you'd gonna have a rows worth of data already loaded up.  it's just a matter is recognizing the request is a letter only and now a row number and fetching it from the current row - there is no need to scan the entire source file. 

If you were looking for pure random access (like accessing any cell from the sheet object), I can see that potentially being a bit more work, but this request is specific to the time that you are iterating rows and just want a column.  In that case, the data is loaded and ready.  

Fixing this just gets rid of otherwise tedious dynamic formatting of cell references (i.e. putting redundant row #s into the key)

**Comment by pythonicrubyist** [comment]
@gduprey can you give me an example of how you think you should parse?

Currently it is like: 

```
sheet.rows.each do |row|
  puts row # => {"A1"=>"Content 1", "B1"=>nil, C1"=>nil, "D1"=>"Content 3"}
end
```

**Comment by pythonicrubyist** [comment]
@gduprey I agree. In order to maintain back-ward compatibility, I would rather not change `rows`. How about keeping `rows` as it and introducing a new one line `simple_rows`. So the code would look like:

```
sheet.simple_rows.each_with_index do |row|
  first_col = row['A']
  second_col = row['C']
  third_col = row['D']

  # Do something with all three columns for this row
end
```
And we keep `rows` untouched. Please let me know what you think.

**Comment by pythonicrubyist** [comment]
done.

**Comment by gduprey** [comment]
Perfect!  Thanks!
