### ISSUE TITLE
Load data is 0 when column content is result of sum in excel

### ISSUE THREAD

**Issue by jaywangactive** [pythonicrubyist/creek#89]
![Screen Shot 2020-01-14 at 09 32 26](https://user-images.githubusercontent.com/35758264/72306099-f7eefc80-36b0-11ea-9158-8b433b206ed8.png)

**Comment by pythonicrubyist** [comment]
Creek is not capable of handling formulas.

**Comment by dannypurcell** [comment]
This should really be noted on the readme. And it's kind of a major bug. Even if Creek is not doing anything with the formula calculation-wise, it should not be altering the cell data. As it is, this bug is converting formula cells with `=HYPERLINK('https://some/link/or/other')` into number types with `0` as the content.

This makes Creek impossible to trust for any actual data work.
